### ISSUE TITLE
Fail to fallback to "download the entire file" using remote URL's

### ISSUE THREAD

**Issue by ManarKamel** [aadsm/jsmediatags#7]
I tried JavaScript ID3 Reader and this jsmediatags,js

They both fail to get tags from external websites that don't support HTTP Range feature or they don't allow If-Modified-Since header.

So I edited jsmediatags.js file:

#1977: Removed: xhr.setRequestHeader("If-Modified-Since", "Sat, 01 Jan 1970 00:00:00 GMT"); 
#1813: Replaced with: var contentLength = null;

What I did ? I forced to download the entire file, which this should be automatically If required headers are not supported on the remote URL's. please fix the fallback ASAP

Example URL: https://crossorigin.me/http://s3.amazonaws.com/static.noisetrade.com/w/8a6a64e5-5c2c-4584-ad46-bba625de301e/hey-tree-streaming.mp3

**Comment by aadsm** [comment]
This is definitely a bug, it should fetch the entire file when Range is not supported.
Thank you for the heads up and the example, let me investigate.

**Comment by ManarKamel** [comment]
That's great, I'm waiting for your new update,

I have to say something, I'm really impressed by this library, I've tried almost EVERY JavaScript ID3 library out there, you have the best JavaScript ID3 library here. It's even memory-efficient,
way better than JavaScript ID3 Reader (It has memory usage problem.. takes 20MB for every song file).

P.S. I've tried `setTagsToRead `on m4a song file.

`.setTagsToRead(["COMM", "TCON", "WXXX"])` this works.
`.setTagsToRead(["comment", "track", "lyrics"])` this doesn't (returns empty tags)

**Comment by aadsm** [comment]
Thank you so much for your kind words!
Let me create a new issue to track down that one. I might only have time to address this on friday / the weekend.

**Comment by aadsm** [comment]
I've just fixed both issues and published a new version on npm.

**Comment by ManarKamel** [comment]
I don't think the problem is fixed, I'm still not able to get tags from CORS-enabled remote URLs.
Could you please check again ?

I have a proposition for you:
You can get arraybuffer or blob using XHR then pass them to JSMediaTags.

**Comment by ManarKamel** [comment]
Or do try and catch for headers, inside catch statement do "fetch the entire file" method

**Comment by aadsm** [comment]
Is this still an issue? It works well for me, I've tried it here: https://tonicdev.com/572393dd79f8ad120098dd9e/572393dd79f8ad120098dd9f

**Comment by ManarKamel** [comment]
It still doesn't work, try it in the browser, it will throw "Request header field If-Modified-Since is not allowed by Access-Control-Allow-Headers in preflight response."

Anyway, I've chosen to remove anything related to "download the entire file", which is a bad experience for users, However the bug still exists.

I recommend "try and catch" solution for headers.
Thanks again for this work.

**Comment by aadsm** [comment]
When you're not able to whitelist the needed headers on the server you need to disallow their usage:
```javascript
jsmediatags.Config.setDisallowedXhrHeaders(['If-Modified-Since', 'Range']);
```
In this particular case it still doesn't work because the request never finishes, maybe crossorigin.me doesn't allow requests greater than 2MB? I'm not sure about the reason but it doesn't timeout so it keeps waiting for more data from the server.
To solve this I added a way to configure the request timeout and default it to 30s.

You're not able to try/catch these XHR errors, you can know about them with the `onerror` event.
